/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderVerificationRouteImport } from './routes/order-verification'
import { Route as OrderTrackingRouteImport } from './routes/order-tracking'
import { Route as OrderFailedRouteImport } from './routes/order-failed'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminSubcategoriesIndexRouteImport } from './routes/admin.subcategories.index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin.categories.index'
import { Route as AdminSubcategoriesCreateRouteImport } from './routes/admin.subcategories.create'
import { Route as AdminProductsCreateRouteImport } from './routes/admin.products.create'
import { Route as AdminCategoriesCreateRouteImport } from './routes/admin.categories.create'
import { Route as AdminSubcategoriesIdEditRouteImport } from './routes/admin.subcategories.$id.edit'
import { Route as AdminProductsIdEditRouteImport } from './routes/admin.products.$id.edit'
import { Route as AdminCategoriesIdEditRouteImport } from './routes/admin.categories.$id.edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderVerificationRoute = OrderVerificationRouteImport.update({
  id: '/order-verification',
  path: '/order-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTrackingRoute = OrderTrackingRouteImport.update({
  id: '/order-tracking',
  path: '/order-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderFailedRoute = OrderFailedRouteImport.update({
  id: '/order-failed',
  path: '/order-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcategoriesIndexRoute = AdminSubcategoriesIndexRouteImport.update({
  id: '/subcategories/',
  path: '/subcategories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcategoriesCreateRoute =
  AdminSubcategoriesCreateRouteImport.update({
    id: '/subcategories/create',
    path: '/subcategories/create',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsCreateRoute = AdminProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesCreateRoute = AdminCategoriesCreateRouteImport.update({
  id: '/categories/create',
  path: '/categories/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubcategoriesIdEditRoute =
  AdminSubcategoriesIdEditRouteImport.update({
    id: '/subcategories/$id/edit',
    path: '/subcategories/$id/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesIdEditRoute = AdminCategoriesIdEditRouteImport.update({
  id: '/categories/$id/edit',
  path: '/categories/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/order-verification': typeof OrderVerificationRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/subcategories/create': typeof AdminSubcategoriesCreateRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/subcategories/': typeof AdminSubcategoriesIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/subcategories/$id/edit': typeof AdminSubcategoriesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/order-verification': typeof OrderVerificationRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/subcategories/create': typeof AdminSubcategoriesCreateRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/subcategories': typeof AdminSubcategoriesIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/subcategories/$id/edit': typeof AdminSubcategoriesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/order-verification': typeof OrderVerificationRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/categories/create': typeof AdminCategoriesCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/subcategories/create': typeof AdminSubcategoriesCreateRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/subcategories/': typeof AdminSubcategoriesIndexRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/products/$id/edit': typeof AdminProductsIdEditRoute
  '/admin/subcategories/$id/edit': typeof AdminSubcategoriesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/order-confirmation'
    | '/order-failed'
    | '/order-tracking'
    | '/order-verification'
    | '/orders'
    | '/products'
    | '/profile'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/users'
    | '/products/$id'
    | '/admin/'
    | '/products/'
    | '/admin/categories/create'
    | '/admin/products/create'
    | '/admin/subcategories/create'
    | '/admin/categories/'
    | '/admin/products/'
    | '/admin/subcategories/'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/subcategories/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/order-confirmation'
    | '/order-failed'
    | '/order-tracking'
    | '/order-verification'
    | '/orders'
    | '/profile'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/users'
    | '/products/$id'
    | '/admin'
    | '/products'
    | '/admin/categories/create'
    | '/admin/products/create'
    | '/admin/subcategories/create'
    | '/admin/categories'
    | '/admin/products'
    | '/admin/subcategories'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/subcategories/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/order-confirmation'
    | '/order-failed'
    | '/order-tracking'
    | '/order-verification'
    | '/orders'
    | '/products'
    | '/profile'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/users'
    | '/products/$id'
    | '/admin/'
    | '/products/'
    | '/admin/categories/create'
    | '/admin/products/create'
    | '/admin/subcategories/create'
    | '/admin/categories/'
    | '/admin/products/'
    | '/admin/subcategories/'
    | '/admin/categories/$id/edit'
    | '/admin/products/$id/edit'
    | '/admin/subcategories/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OrderFailedRoute: typeof OrderFailedRoute
  OrderTrackingRoute: typeof OrderTrackingRoute
  OrderVerificationRoute: typeof OrderVerificationRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-verification': {
      id: '/order-verification'
      path: '/order-verification'
      fullPath: '/order-verification'
      preLoaderRoute: typeof OrderVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-tracking': {
      id: '/order-tracking'
      path: '/order-tracking'
      fullPath: '/order-tracking'
      preLoaderRoute: typeof OrderTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-failed': {
      id: '/order-failed'
      path: '/order-failed'
      fullPath: '/order-failed'
      preLoaderRoute: typeof OrderFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategories/': {
      id: '/admin/subcategories/'
      path: '/subcategories'
      fullPath: '/admin/subcategories/'
      preLoaderRoute: typeof AdminSubcategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategories/create': {
      id: '/admin/subcategories/create'
      path: '/subcategories/create'
      fullPath: '/admin/subcategories/create'
      preLoaderRoute: typeof AdminSubcategoriesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/create': {
      id: '/admin/products/create'
      path: '/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminProductsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/create': {
      id: '/admin/categories/create'
      path: '/categories/create'
      fullPath: '/admin/categories/create'
      preLoaderRoute: typeof AdminCategoriesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subcategories/$id/edit': {
      id: '/admin/subcategories/$id/edit'
      path: '/subcategories/$id/edit'
      fullPath: '/admin/subcategories/$id/edit'
      preLoaderRoute: typeof AdminSubcategoriesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id/edit': {
      id: '/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories/$id/edit': {
      id: '/admin/categories/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/admin/categories/$id/edit'
      preLoaderRoute: typeof AdminCategoriesIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCategoriesCreateRoute: typeof AdminCategoriesCreateRoute
  AdminProductsCreateRoute: typeof AdminProductsCreateRoute
  AdminSubcategoriesCreateRoute: typeof AdminSubcategoriesCreateRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminSubcategoriesIndexRoute: typeof AdminSubcategoriesIndexRoute
  AdminCategoriesIdEditRoute: typeof AdminCategoriesIdEditRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
  AdminSubcategoriesIdEditRoute: typeof AdminSubcategoriesIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCategoriesCreateRoute: AdminCategoriesCreateRoute,
  AdminProductsCreateRoute: AdminProductsCreateRoute,
  AdminSubcategoriesCreateRoute: AdminSubcategoriesCreateRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminSubcategoriesIndexRoute: AdminSubcategoriesIndexRoute,
  AdminCategoriesIdEditRoute: AdminCategoriesIdEditRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
  AdminSubcategoriesIdEditRoute: AdminSubcategoriesIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OrderFailedRoute: OrderFailedRoute,
  OrderTrackingRoute: OrderTrackingRoute,
  OrderVerificationRoute: OrderVerificationRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
